spring:
    datasource:
        url: jdbc:h2:mem:springboot_demo
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        # http://localhost:8080/h2-console
        console.enabled: true
